
  _extends: .github

  branches:
  - name: master
    protection:
      required_pull_request_reviews:
        dismissal_restrictions:
          teams:
            - everydollar
      restrictions:
        teams:
          - everydollar